[package]
name = "eyescare-platform-win"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
eyescare-platform = { path = "../eyescare-platform" }
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Devices_Display",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_ColorSystem",
    "Win32_System_Threading",
    "Win32_System_Registry",
    "Win32_System_SystemInformation",
    "Win32_System_RemoteDesktop",
    "Win32_Security",
] }
tracing = { workspace = true }
